variables:
  DOCKER_DRIVER: overlay
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

cache:
  key: "$CI_PROJECT_NAME"
  untracked: false
  policy: push

stages:
  - test
  - build
  - release
  - deploy

review_app:
  image: alpine:latest
  stage: test
  script:
    - echo "Reviewing app" 
    - make test
  only:
    - branches
  except: 
    - master

build_app:
  image: alpine:latest
  stage: build
  script: 
    - echo "Building the app"
    - make build
  artifacts:
    paths:
    - .build
    expire_in: 1 week
  tags:
    - docker
  when: manual
  only: 
    - release

test_app:
  image: alpine:latest
  stage: test
  script:
    - echo "Testing app"
    - make test
  tags:
    - docker
  only:
    - master
  artifacts:
    paths:
    - .build
  
release_image:
  image: docker:latest
  stage: release
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE -f Dockerfile .
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_IMAGE:latest
    - docker push $CONTAINER_IMAGE:latest
  when: manual
  tags:
    - docker
  only: 
    - release

deploy_review:
  stage: deploy
  script:
    - echo "Deploy a review app"
  environment:
    name: review/$CI_BUILD_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.admin.naamio.cloud
  only:
    - branches
  except:
    - master

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://staging.admin.naamio.cloud
  only:
  - master
  artifacts:
    paths:
    - public
  only:
  - master

deploy_release:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://admin.naamio.cloud
  artifacts:
    paths:
    - public
  when: manual
  only:
  - release

pages:
  script:
    - echo "Deploying pages"
  artifacts:
    paths:
    - public
  when: manual
  only:
  - release

