image: alpine:latest

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: echo "Running tests"

build:
  stage: build
  script: echo "Building the app"

deploy_review:
  stage: deploy
  script:
    - echo "Deploy a review app"
  environment:
    name: review/$CI_BUILD_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.admin.naamio.cloud
  only:
    - branches
  except:
    - master

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://staging.admin.naamio.cloud
  only:
  - master
  artifacts:
    paths:
    - public
  only:
  - master

deploy_release:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://admin.naamio.cloud
  artifacts:
    paths:
    - public
  when: manual
  only:
  - release

pages:
  script:
    - echo "Deploying pages"
  artifacts:
    paths:
    - public
  when: manual
  only:
  - release

